language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ethnopunk/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true ethnopunk/react-test npm test

after_success:
  - docker build -t ethnopunk/multi-client ./client
  - docker build -t ethnopunk/multi-nginx ./nginx
  - docker build -t ethnopunk/multi-server ./server
  - docker build -t ethnopunk/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push ethnopunk/multi-client
  - docker push ethnopunk/multi-nginx
  - docker push ethnopunk/multi-server
  - docker push ethnopunk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-cloud
  env: MultiCloud-env
  bucket_name: elasticbeanstalk-us-west-2-338430314199
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



